# Generated by Django 5.2.15 on 2026-06-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_customer_email_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_session_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('expired', 'Expirado'), ('refunded', 'Reembolsado')], db_index=True, default='pending_payment', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
