# Generated by Django 5.2.15 on 2026-06-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_is_active_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('preparing', 'En preparación'), ('ready_for_pickup', 'Listo para retiro'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado operativo')], db_index=True, default='pending', max_length=30),
        ),
    ]
