# Generated by Django 5.2.15 on 2026-06-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_fulfillment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='accepted_warranty_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='address_line',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('pickup_store', 'Recojo en tienda'), ('delivery_arequipa', 'Delivery Arequipa'), ('national_shipping', 'Envío nacional')], db_index=True, max_length=25),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='document_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='document_type',
            field=models.CharField(blank=True, choices=[('dni', 'DNI'), ('ruc', 'RUC'), ('ce', 'Carnet de Extranjería')], max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_type',
            field=models.CharField(blank=True, choices=[('boleta', 'Boleta'), ('factura', 'Factura')], max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
