# Generated by Django 5.2.15 on 2026-06-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_commercial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email_send_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='internal_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
