# Generated by Django 5.2.15 on 2026-08-26 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_email_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Emitida'), ('void', 'Anulada')], db_index=True, default='issued', max_length=30)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_notes_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_note', to='store.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('initial_stock', 'Stock inicial'), ('purchase_entry', 'Entrada por compra'), ('manual_entry', 'Entrada manual'), ('return_entry', 'Entrada por devolución'), ('correction_positive', 'Corrección positiva'), ('manual_exit', 'Salida manual'), ('sale_exit', 'Salida por venta'), ('correction_negative', 'Corrección negativa'), ('damaged_exit', 'Salida por daño / merma'), ('service_exit', 'Salida por servicio técnico')], db_index=True, max_length=40)),
                ('quantity', models.PositiveIntegerField()),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='store.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='store_stock_product_e003b4_idx'), models.Index(fields=['movement_type', '-created_at'], name='store_stock_movemen_d73ab4_idx'), models.Index(fields=['order', 'movement_type'], name='store_stock_order_i_c6a713_idx')],
            },
        ),
    ]
