# Generated by Django 5.2.15 on 2026-08-26 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_seed_pilot_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='store.company')),
            ],
            options={
                'ordering': ['company__name', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='store.company')),
            ],
            options={
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='store.companyarea')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='store.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='store.companyrole')),
            ],
            options={
                'ordering': ['membership__company__name', 'role__name'],
            },
        ),
        migrations.AddIndex(
            model_name='companyarea',
            index=models.Index(fields=['company', 'is_active'], name='store_compa_company_747119_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyarea',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='unique_area_slug_per_company'),
        ),
        migrations.AddConstraint(
            model_name='companyarea',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_area_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='companyrole',
            index=models.Index(fields=['company', 'is_active'], name='store_compa_company_cd668f_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyrole',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='unique_role_slug_per_company'),
        ),
        migrations.AddConstraint(
            model_name='companyrole',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_role_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='membershiproleassignment',
            index=models.Index(fields=['membership', 'is_active'], name='store_membe_members_2e8e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='membershiproleassignment',
            index=models.Index(fields=['role', 'is_active'], name='store_membe_role_id_93aafa_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershiproleassignment',
            constraint=models.UniqueConstraint(fields=('membership', 'role', 'area'), name='unique_role_assignment_per_area'),
        ),
    ]
