# Generated by Django 5.2.15 on 2026-08-27 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_catalog_company_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='store.company'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.company'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['company', 'code'], name='store_coupo_company_014986_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', '-created_at'], name='store_order_company_bd3c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'paid_at'], name='store_order_company_836201_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'status'], name='store_order_company_e7d02d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'fulfillment_status'], name='store_order_company_f5b010_idx'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_coupon_code_per_company'),
        ),
    ]
