"""
Phase 4, step 1 of 2 — SCHEMA.

  0031  Customer, Order.customer, constraints and indexes          (this file)
  0032  attach existing orders to customers, deterministically only

The schema is safe to apply on its own: `Order.customer` is nullable, so every
existing order stays valid and unlinked until 0032 decides — conservatively —
which of them can be attributed to somebody with certainty.
"""

# Generated by Django 5.2.15 on 2026-08-31 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_backfill_internal_sequences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('person', 'Persona'), ('business', 'Empresa')], db_index=True, default='person', max_length=16)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('document_type', models.CharField(blank=True, choices=[('dni', 'DNI'), ('ruc', 'RUC'), ('ce', 'Carnet de Extranjería')], max_length=10)),
                ('document_number', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line', models.CharField(blank=True, max_length=300)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='store.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'business_name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.customer'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'is_active'], name='store_custo_company_f1a500_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'document_number'], name='store_custo_company_f4f775_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'email'], name='store_custo_company_a82b93_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'phone'], name='store_custo_company_734618_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'created_at'], name='store_custo_company_db08d9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'last_name', 'first_name'], name='store_custo_company_92ccc8_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'business_name'], name='store_custo_company_09c112_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('company', 'user'), name='unique_customer_per_user_per_company'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number', ''), _negated=True), fields=('company', 'document_type', 'document_number'), name='unique_customer_document_per_company'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('first_name', ''), _negated=True), models.Q(('last_name', ''), _negated=True), models.Q(('business_name', ''), _negated=True), models.Q(('document_number', ''), _negated=True), _connector='OR'), name='customer_has_some_identity'),
        ),
    ]
