"""
Commercial Phase C1 — schema.

  ProductBarcode                    scannable codes, one article per code per company
  Order.sales_channel               online | pos
  Order.payment_method              stripe | cash | card | transfer | other
  Order.sold_by                     who rang it up (null for online and history)
  Order.pos_idempotency_key         + fingerprint: a double click cannot charge twice
  BranchStock.safety_stock          buffer used by the replenishment arithmetic
  BranchStock.lead_time_days        0 = unconfigured, NOT "arrives instantly"

NO DATA MIGRATION IS NEEDED, AND THAT IS DELIBERATE
---------------------------------------------------
`sales_channel` defaults to `online` and `payment_method` to `stripe`. Every
order that exists today was placed through the storefront and paid through
Stripe, so the column defaults ARE the historical truth rather than a guess —
there is nothing to infer and nothing to backfill.

The new POS columns are blank/null for that history, which is also correct: no
counter sold those, and no idempotency key was ever issued for them. The
conditional unique on `pos_idempotency_key` exists precisely so that the empty
string on thousands of historical rows does not collide with itself.

Totals, statuses, customer snapshots, Stripe identifiers, company and branch are
untouched.
"""

# Generated by Django 5.2.15 on 2026-08-31 07:48

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_customer_capabilities_for_untouched_admin_presets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, validators=[store.models.validate_barcode])),
                ('symbology', models.CharField(choices=[('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upca', 'UPC-A'), ('code128', 'Code 128'), ('code39', 'Code 39'), ('internal', 'Código interno'), ('unknown', 'Sin especificar')], default='unknown', max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_primary', 'code'],
            },
        ),
        migrations.AddField(
            model_name='branchstock',
            name='lead_time_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='safety_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe (online)'), ('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('other', 'Otro')], db_index=True, default='stripe', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='pos_idempotency_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='pos_request_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_channel',
            field=models.CharField(choices=[('online', 'Tienda online'), ('pos', 'Punto de venta')], db_index=True, default='online', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'sales_channel', 'paid_at'], name='store_order_company_babcf1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'sold_by', 'paid_at'], name='store_order_company_b2e49c_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('pos_idempotency_key', ''), _negated=True), fields=('company', 'pos_idempotency_key'), name='unique_pos_idempotency_key_per_company'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_barcodes', to='store.company'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='store.product'),
        ),
        migrations.AddIndex(
            model_name='productbarcode',
            index=models.Index(fields=['company', 'code'], name='store_produ_company_78d635_idx'),
        ),
        migrations.AddIndex(
            model_name='productbarcode',
            index=models.Index(fields=['product', 'is_active'], name='store_produ_product_592239_idx'),
        ),
        migrations.AddConstraint(
            model_name='productbarcode',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_barcode_per_company'),
        ),
        migrations.AddConstraint(
            model_name='productbarcode',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_barcode_per_product'),
        ),
    ]
