# Generated by Django 5.2.15 on 2026-09-01 13:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_checkout_idempotency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalsequence',
            name='document_type',
            field=models.CharField(choices=[('sales_note', 'Nota de venta interna'), ('repair_order', 'Orden de servicio técnico')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('phone', 'Teléfono'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('desktop', 'Computadora de escritorio'), ('console', 'Consola'), ('wearable', 'Wearable'), ('other', 'Otro')], db_index=True, default='other', max_length=16)),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=80)),
                ('imei', models.CharField(blank=True, max_length=32)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('storage_capacity', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='store.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='store.customer')),
            ],
            options={
                'ordering': ['brand', 'model', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('sequence_value', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('diagnosing', 'En diagnóstico'), ('waiting_approval', 'Esperando aprobación'), ('cancelled', 'Cancelado')], db_index=True, default='received', max_length=32)),
                ('reported_issue', models.TextField(max_length=2000)),
                ('physical_condition', models.TextField(blank=True, max_length=2000)),
                ('received_accessories', models.TextField(blank=True, max_length=1000)),
                ('internal_notes', models.TextField(blank=True, max_length=2000)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_orders', to='store.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_orders', to='store.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_orders', to='store.customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_orders', to='store.device')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_orders_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RepairStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('received', 'Recibido'), ('diagnosing', 'En diagnóstico'), ('waiting_approval', 'Esperando aprobación'), ('cancelled', 'Cancelado')], max_length=32)),
                ('to_status', models.CharField(choices=[('received', 'Recibido'), ('diagnosing', 'En diagnóstico'), ('waiting_approval', 'Esperando aprobación'), ('cancelled', 'Cancelado')], max_length=32)),
                ('origin', models.CharField(choices=[('internal', 'Personal interno'), ('customer', 'Cliente'), ('system', 'Sistema'), ('integration', 'Integración')], default='internal', max_length=16)),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('is_customer_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_status_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_status_events', to='store.company')),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='store.repairorder')),
            ],
            options={
                'verbose_name_plural': 'repair status history',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RepairStatusSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('received', 'Recibido'), ('diagnosing', 'En diagnóstico'), ('waiting_approval', 'Esperando aprobación'), ('cancelled', 'Cancelado')], db_index=True, max_length=32)),
                ('label', models.CharField(max_length=60)),
                ('is_customer_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_status_settings', to='store.company')),
            ],
            options={
                'ordering': ['company', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician_assignments', to='store.company')),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='store.repairorder')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'customer'], name='store_devic_company_443348_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'serial_number'], name='store_devic_company_8c7690_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'imei'], name='store_devic_company_77343d_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'brand', 'model'], name='store_devic_company_d6f254_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'created_at'], name='store_devic_company_fcb8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='repairorder',
            index=models.Index(fields=['company', 'status'], name='store_repai_company_6fdf9a_idx'),
        ),
        migrations.AddIndex(
            model_name='repairorder',
            index=models.Index(fields=['company', 'branch', 'status'], name='store_repai_company_8e18bc_idx'),
        ),
        migrations.AddIndex(
            model_name='repairorder',
            index=models.Index(fields=['company', 'customer'], name='store_repai_company_c34aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='repairorder',
            index=models.Index(fields=['company', 'received_at'], name='store_repai_company_6d3e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='repairorder',
            index=models.Index(fields=['device'], name='store_repai_device__59600d_idx'),
        ),
        migrations.AddConstraint(
            model_name='repairorder',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_repair_order_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='repairstatushistory',
            index=models.Index(fields=['repair_order', 'created_at'], name='store_repai_repair__07928a_idx'),
        ),
        migrations.AddIndex(
            model_name='repairstatushistory',
            index=models.Index(fields=['company', 'created_at'], name='store_repai_company_f523f0_idx'),
        ),
        migrations.AddIndex(
            model_name='repairstatussetting',
            index=models.Index(fields=['company', 'sort_order'], name='store_repai_company_4f3a2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='repairstatussetting',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_repair_status_per_company'),
        ),
        migrations.AddIndex(
            model_name='technicianassignment',
            index=models.Index(fields=['company', 'technician'], name='store_techn_company_d34f38_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianassignment',
            index=models.Index(fields=['repair_order', 'assigned_at'], name='store_techn_repair__09703a_idx'),
        ),
        migrations.AddConstraint(
            model_name='technicianassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('unassigned_at__isnull', True)), fields=('repair_order',), name='unique_active_assignment_per_repair_order'),
        ),
    ]
