"""
Commercial Phase C1.2 — the enriched counter sale.

  Membership.commission_rate_percent   the deal, per employment
  SalesCommission                      the obligation, frozen at the sale
  Order.seller_name_snapshot           who is credited, in text
  Order.discount_source/_reason        why money came off, and on whose say-so
  Order.discount_authorized_by
  Order.amount_received/change_amount  cash and change, null when not cash
  Order.payment_reference              an operation number, never a credential
  Order.external_reference, sale_notes named optional fields, not a JSON blob

NOTHING HISTORICAL IS REWRITTEN
-------------------------------
Every column is nullable or carries a default that is true of the past:
`discount_source` defaults to `none`, which is what every historical order was;
`commission_rate_percent` defaults to 0, which is what every existing employment
had agreed (none); the cash fields default to NULL, which is correct for online
orders that never saw a till.

No commission rows are created for past sales. Inventing them would fabricate
debts the company never incurred, to sellers that historical orders never named.
Totals, discounts, coupon codes, customer snapshots, Stripe identifiers and
stock are untouched.
"""

# Generated by Django 5.2.15 on 2026-08-31 16:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_commercial_capabilities_for_untouched_presets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('accrued', 'Devengada'), ('voided', 'Anulada')], db_index=True, default='accrued', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='commission_rate_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_source',
            field=models.CharField(choices=[('none', 'Sin descuento'), ('coupon', 'Código promocional'), ('manual', 'Descuento manual')], db_index=True, default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_notes',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate_percent__gte', Decimal('0.00')), ('commission_rate_percent__lte', Decimal('100.00'))), name='membership_commission_rate_within_range'),
        ),
        migrations.AddField(
            model_name='salescommission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_commissions', to='store.company'),
        ),
        migrations.AddField(
            model_name='salescommission',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_commission', to='store.order'),
        ),
        migrations.AddField(
            model_name='salescommission',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='salescommission',
            index=models.Index(fields=['company', 'seller', 'created_at'], name='store_sales_company_4f69bb_idx'),
        ),
        migrations.AddIndex(
            model_name='salescommission',
            index=models.Index(fields=['company', 'status'], name='store_sales_company_513b39_idx'),
        ),
        migrations.AddConstraint(
            model_name='salescommission',
            constraint=models.CheckConstraint(condition=models.Q(('rate_percent__gte', Decimal('0.00')), ('rate_percent__lte', Decimal('100.00'))), name='commission_rate_within_range'),
        ),
        migrations.AddConstraint(
            model_name='salescommission',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='commission_amount_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='salescommission',
            constraint=models.CheckConstraint(condition=models.Q(('base_amount__gte', Decimal('0.00'))), name='commission_base_not_negative'),
        ),
    ]
