# Generated by Django 5.2.17 on 2026-09-01 20:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_service_capabilities_for_untouched_admin_presets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairorder',
            name='status',
            field=models.CharField(choices=[('received', 'Recibido'), ('diagnosing', 'En diagnóstico'), ('waiting_approval', 'Esperando aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], db_index=True, default='received', max_length=32),
        ),
        migrations.AlterField(
            model_name='repairstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('received', 'Recibido'), ('diagnosing', 'En diagnóstico'), ('waiting_approval', 'Esperando aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], max_length=32),
        ),
        migrations.AlterField(
            model_name='repairstatushistory',
            name='to_status',
            field=models.CharField(choices=[('received', 'Recibido'), ('diagnosing', 'En diagnóstico'), ('waiting_approval', 'Esperando aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], max_length=32),
        ),
        migrations.AlterField(
            model_name='repairstatussetting',
            name='code',
            field=models.CharField(choices=[('received', 'Recibido'), ('diagnosing', 'En diagnóstico'), ('waiting_approval', 'Esperando aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='RepairDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('finalized', 'Finalizado')], db_index=True, default='draft', max_length=16)),
                ('description', models.TextField(max_length=4000)),
                ('root_cause', models.TextField(blank=True, max_length=2000)),
                ('recommended_action', models.TextField(max_length=4000)),
                ('internal_notes', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_diagnostics', to='store.company')),
                ('diagnosed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_diagnostics', to=settings.AUTH_USER_MODEL)),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostics', to='store.repairorder')),
            ],
            options={
                'ordering': ['-revision', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RepairQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Anulada')], db_index=True, default='draft', max_length=16)),
                ('currency', models.CharField(max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True, max_length=2000)),
                ('internal_notes', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_quotes', to='store.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_quotes_created', to=settings.AUTH_USER_MODEL)),
                ('diagnostic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='store.repairdiagnostic')),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='store.repairorder')),
            ],
            options={
                'ordering': ['-revision', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RepairQuoteDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Aprobada'), ('reject', 'Rechazada')], max_length=16)),
                ('channel', models.CharField(choices=[('customer_account', 'Cuenta del cliente')], default='customer_account', max_length=32)),
                ('reason', models.TextField(blank=True, max_length=1000)),
                ('quoted_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_quote_decisions', to='store.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_quote_decisions', to='store.customer')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='store.repairquote')),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_decisions', to='store.repairorder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_quote_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-decided_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RepairQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('labor', 'Mano de obra'), ('part', 'Repuesto'), ('service', 'Servicio')], default='labor', max_length=16)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repair_quote_items', to='store.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.repairquote')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='repairdiagnostic',
            index=models.Index(fields=['company', 'status'], name='store_repai_company_130600_idx'),
        ),
        migrations.AddIndex(
            model_name='repairdiagnostic',
            index=models.Index(fields=['repair_order', 'revision'], name='store_repai_repair__6b2f92_idx'),
        ),
        migrations.AddConstraint(
            model_name='repairdiagnostic',
            constraint=models.UniqueConstraint(fields=('repair_order', 'revision'), name='unique_diagnostic_revision_per_order'),
        ),
        migrations.AddIndex(
            model_name='repairquote',
            index=models.Index(fields=['company', 'status'], name='store_repai_company_dbd296_idx'),
        ),
        migrations.AddIndex(
            model_name='repairquote',
            index=models.Index(fields=['repair_order', 'revision'], name='store_repai_repair__baca38_idx'),
        ),
        migrations.AddIndex(
            model_name='repairquote',
            index=models.Index(fields=['company', 'sent_at'], name='store_repai_company_dd35bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='repairquote',
            constraint=models.UniqueConstraint(fields=('repair_order', 'revision'), name='unique_quote_revision_per_order'),
        ),
        migrations.AddConstraint(
            model_name='repairquote',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', Decimal('0.00'))), name='repair_quote_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='repairquote',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', Decimal('0.00'))), name='repair_quote_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='repairquotedecision',
            index=models.Index(fields=['company', 'decided_at'], name='store_repai_company_d9ecb7_idx'),
        ),
        migrations.AddIndex(
            model_name='repairquotedecision',
            index=models.Index(fields=['repair_order'], name='store_repai_repair__897543_idx'),
        ),
        migrations.AddIndex(
            model_name='repairquoteitem',
            index=models.Index(fields=['quote', 'sort_order'], name='store_repai_quote_i_03bcbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='repairquoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0.00'))), name='repair_quote_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='repairquoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', Decimal('0.00'))), name='repair_quote_item_price_non_negative'),
        ),
    ]
