# Generated by Django 5.2.15 on 2026-08-31 23:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_backfill_historical_discount_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_source',
            field=models.CharField(choices=[('none', 'Sin descuento'), ('coupon', 'Código promocional'), ('manual', 'Descuento manual'), ('promotion', 'Promoción automática')], db_index=True, default='none', max_length=10),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('promotion_type', models.CharField(choices=[('bundle_fixed_price', 'Combo a precio fijo'), ('bundle_percent', 'Combo con porcentaje de descuento')], max_length=24)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('branch_scope', models.CharField(choices=[('all', 'Todas las sucursales'), ('selected', 'Sucursales seleccionadas')], default='all', max_length=10)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_applications_per_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='store.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AppliedPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name_snapshot', models.CharField(max_length=150)),
                ('promotion_type_snapshot', models.CharField(max_length=24)),
                ('applications', models.PositiveSmallIntegerField(default=1)),
                ('regular_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_promotions', to='store.company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_promotions', to='store.order')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='store.promotion')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PromotionBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='store.branch')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='store.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_items', to='store.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.promotion')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['company', 'is_active', 'priority'], name='store_promo_company_019c4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_promotion_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__isnull', True), models.Q(('discount_percent__gt', Decimal('0.00')), ('discount_percent__lte', Decimal('100.00'))), _connector='OR'), name='promotion_percent_within_range'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_price__isnull', True), ('fixed_price__gte', Decimal('0.00')), _connector='OR'), name='promotion_fixed_price_not_negative'),
        ),
        migrations.AddIndex(
            model_name='appliedpromotion',
            index=models.Index(fields=['company', 'promotion', 'created_at'], name='store_appli_company_6ddfec_idx'),
        ),
        migrations.AddConstraint(
            model_name='appliedpromotion',
            constraint=models.UniqueConstraint(fields=('order', 'promotion'), name='unique_applied_promotion_per_order'),
        ),
        migrations.AddConstraint(
            model_name='appliedpromotion',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', Decimal('0.00'))), name='applied_promotion_discount_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='promotionbranch',
            constraint=models.UniqueConstraint(fields=('promotion', 'branch'), name='unique_promotion_branch'),
        ),
        migrations.AddConstraint(
            model_name='promotionitem',
            constraint=models.UniqueConstraint(fields=('promotion', 'product'), name='unique_promotion_item'),
        ),
        migrations.AddConstraint(
            model_name='promotionitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='promotion_item_quantity_positive'),
        ),
    ]
