# Generated by Django 5.2.17 on 2026-09-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_consolidate_duplicate_lines'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('session_key', 'product'), name='unique_cart_line_per_session'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_order_line_per_product'),
        ),
    ]
