# Generated by Django 5.2.15 on 2026-09-01 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_merge_checkout_and_commercial_graphs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('products', 'Productos'), ('stock', 'Inventario')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('previewed', 'Previsualizado'), ('applied', 'Aplicado'), ('failed', 'Fallido')], db_index=True, default='previewed', max_length=16)),
                ('stock_mode', models.CharField(blank=True, choices=[('initial', 'Carga inicial'), ('reconcile_target', 'Ajuste a stock objetivo')], default='', max_length=20)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('mapping_snapshot', models.JSONField(blank=True, default=dict)),
                ('options_snapshot', models.JSONField(blank=True, default=dict)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_create', models.PositiveIntegerField(default=0)),
                ('rows_update', models.PositiveIntegerField(default=0)),
                ('rows_no_change', models.PositiveIntegerField(default=0)),
                ('rows_skip', models.PositiveIntegerField(default=0)),
                ('rows_error', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs_applied', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to='store.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BulkImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(blank=True, default='', max_length=120)),
                ('row_number', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('no_change', 'Sin cambios'), ('skip', 'Omitir'), ('error', 'Error')], db_index=True, max_length=12)),
                ('match_key', models.CharField(blank=True, default='', max_length=120)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='store.bulkimportjob')),
            ],
            options={
                'ordering': ['sheet_name', 'row_number', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ImportMappingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('import_type', models.CharField(choices=[('products', 'Productos'), ('stock', 'Inventario')], db_index=True, max_length=16)),
                ('header_signature', models.CharField(db_index=True, max_length=64)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_profiles', to='store.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_profiles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkimportjob',
            index=models.Index(fields=['company', 'import_type', '-created_at'], name='store_bulki_company_30122c_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkimportjob',
            index=models.Index(fields=['company', 'status'], name='store_bulki_company_b883fa_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkimportrow',
            index=models.Index(fields=['job', 'action'], name='store_bulki_job_id_fbea64_idx'),
        ),
        migrations.AddIndex(
            model_name='importmappingprofile',
            index=models.Index(fields=['company', 'import_type', 'is_active'], name='store_impor_company_aa04c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='importmappingprofile',
            constraint=models.UniqueConstraint(fields=('company', 'import_type', 'header_signature'), name='unique_import_profile_per_signature'),
        ),
    ]
