"""
M11 / BR-005D — the inspection, and the list it inspects against.

WHAT THIS ADDS
--------------
· `QualityChecklistTemplate` / `QualityChecklistTemplateItem` — what a company
  tests, optionally per device type. The smallest thing that adapts: a named
  list of points a tenant owns. No field types, no conditional logic, no
  scoring — a checklist is a list of things somebody looks at and marks, and
  building a form engine to express that would be building a product nobody
  asked for.
· `QualityCheck` / `QualityCheckItem` — ONE inspection, holding a COPY of the
  list rather than a reference to it. An administrator who edits the template
  tomorrow must not rewrite what was tested today.
· Two lifecycle codes, `quality_control` and `ready_for_pickup`.

The seeding of those codes and of each company's default checklist is the NEXT
migration, and the capability grant the one after. Same triptych as M8, M9 and
M10: schema, frozen data copy, capability.
"""
# Generated by Django 5.2.17 on 2026-09-02 16:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_service_capabilities_for_untouched_technician_presets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairorder',
            name='status',
            field=models.CharField(choices=[('received', 'Recibido'), ('diagnosing', 'En diagnóstico'), ('waiting_approval', 'Esperando aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('in_repair', 'En reparación'), ('waiting_parts', 'Esperando repuestos'), ('repaired', 'Reparado'), ('quality_control', 'En control de calidad'), ('ready_for_pickup', 'Listo para recoger'), ('cancelled', 'Cancelado')], db_index=True, default='received', max_length=32),
        ),
        migrations.AlterField(
            model_name='repairstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('received', 'Recibido'), ('diagnosing', 'En diagnóstico'), ('waiting_approval', 'Esperando aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('in_repair', 'En reparación'), ('waiting_parts', 'Esperando repuestos'), ('repaired', 'Reparado'), ('quality_control', 'En control de calidad'), ('ready_for_pickup', 'Listo para recoger'), ('cancelled', 'Cancelado')], max_length=32),
        ),
        migrations.AlterField(
            model_name='repairstatushistory',
            name='to_status',
            field=models.CharField(choices=[('received', 'Recibido'), ('diagnosing', 'En diagnóstico'), ('waiting_approval', 'Esperando aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('in_repair', 'En reparación'), ('waiting_parts', 'Esperando repuestos'), ('repaired', 'Reparado'), ('quality_control', 'En control de calidad'), ('ready_for_pickup', 'Listo para recoger'), ('cancelled', 'Cancelado')], max_length=32),
        ),
        migrations.AlterField(
            model_name='repairstatussetting',
            name='code',
            field=models.CharField(choices=[('received', 'Recibido'), ('diagnosing', 'En diagnóstico'), ('waiting_approval', 'Esperando aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('in_repair', 'En reparación'), ('waiting_parts', 'Esperando repuestos'), ('repaired', 'Reparado'), ('quality_control', 'En control de calidad'), ('ready_for_pickup', 'Listo para recoger'), ('cancelled', 'Cancelado')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='QualityChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('device_type', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_templates', to='store.company')),
            ],
            options={
                'ordering': ['company', 'device_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('in_progress', 'En curso'), ('passed', 'Aprobado'), ('failed', 'Rechazado')], db_index=True, default='in_progress', max_length=16)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks_started', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_checks', to='store.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks_completed', to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_checks', to='store.repairexecution')),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_checks', to='store.repairorder')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='store.qualitychecklisttemplate')),
            ],
            options={
                'ordering': ['-started_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='QualityChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.qualitychecklisttemplate')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=True)),
                ('result', models.CharField(blank=True, choices=[('pass', 'Correcto'), ('fail', 'Falla'), ('not_applicable', 'No aplica')], max_length=16)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quality_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.qualitycheck')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'indexes': [models.Index(fields=['quality_check', 'sort_order'], name='store_quali_quality_727e28_idx')],
                'constraints': [models.UniqueConstraint(fields=('quality_check', 'code'), name='unique_quality_result_code_per_check')],
            },
        ),
        migrations.AddIndex(
            model_name='qualitychecklisttemplate',
            index=models.Index(fields=['company', 'is_active'], name='store_quali_company_032799_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualitychecklisttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'device_type'), name='one_active_quality_template_per_device_type'),
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['company', 'started_at'], name='store_quali_company_e93394_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['repair_order', 'started_at'], name='store_quali_repair__496cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycheck',
            index=models.Index(fields=['execution'], name='store_quali_executi_5f61df_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualitycheck',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('repair_order',), name='one_open_quality_check_per_repair_order'),
        ),
        migrations.AddConstraint(
            model_name='qualitychecklisttemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='unique_quality_item_code_per_template'),
        ),
    ]
