"""
M11 — make a duplicate role assignment impossible, not merely unlikely.

The pre-existing `unique_role_assignment_per_area` looked like it covered this
and did not: `area` is nullable, two NULLs never compare equal, and the common
case — a role granted with no area — slipped straight through. Measured against
a real database before writing this, not inferred.

A partial unique index is the right shape because the condition IS the gap:
`WHERE area IS NULL`. The two constraints together now say what the model
always claimed — the same role, once per area, and once with no area.

Runs after 0055 has collapsed any duplicates the old gap allowed in.
"""

# Generated by Django 5.2.17 on 2026-09-02 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_consolidate_duplicate_role_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membershiproleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', True)), fields=('membership', 'role'), name='unique_role_assignment_without_area'),
        ),
    ]
