# Generated by Django 5.2.17 on 2026-09-02 22:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_migrate_legacy_technicians_to_rbac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='require_service_payment_before_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RepairPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('method', models.CharField(choices=[('online', 'Pago en línea'), ('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('other', 'Otro')], max_length=16)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=64)),
                ('request_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=300)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_payments', to='store.company')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_payments_received', to=settings.AUTH_USER_MODEL)),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='store.repairorder')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_payments_reversed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-pk'],
                'indexes': [models.Index(fields=['company', 'received_at'], name='store_repai_company_8da1c4_idx'), models.Index(fields=['repair_order', 'received_at'], name='store_repai_repair__2fbbb5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='unique_repair_payment_idempotency_key_per_company'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='repair_payment_amount_positive'), models.CheckConstraint(condition=models.Q(('method', 'online'), _negated=True), name='repair_payment_method_is_not_online_yet')],
            },
        ),
    ]
