# Generated by Django 5.2.17 on 2026-09-02 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Renumbered from 0058 in M12B.1. Two branches independently claimed that
    # number — the payment ledger reached master first — and while a duplicate
    # numeric prefix is legal (a migration's identity is its name plus its
    # dependencies), TWO LEAVES ARE NOT. Depending on 0059 rather than 0057
    # puts this back in a single chain and keeps the file name honest about
    # where in the order it actually runs.
    dependencies = [
        ('store', '0059_payment_capability_for_untouched_presets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('event_key', models.CharField(max_length=200, unique=True)),
                ('target_type', models.CharField(blank=True, max_length=32)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='store.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('internal', 'Interno'), ('customer', 'Cliente')], db_index=True, max_length=16)),
                ('source', models.CharField(choices=[('system', 'Evento del sistema'), ('announcement', 'Comunicado')], default='system', max_length=16)),
                ('title', models.CharField(max_length=140)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('priority', models.CharField(choices=[('info', 'Informativa'), ('action', 'Requiere acción'), ('warning', 'Advertencia'), ('critical', 'Crítica')], default='info', max_length=16)),
                ('target_type', models.CharField(blank=True, max_length=32)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='store.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='store.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='store.notificationevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Correo')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('failed', 'Fallida'), ('skipped', 'Omitida')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='store.notification')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'channel'], name='store_notif_status_45b4a1_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'channel'), name='unique_delivery_per_notification_channel')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['company', 'event_type', 'created_at'], name='store_notif_company_b4f8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['company', 'user', 'read_at', '-created_at'], name='notif_internal_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['company', 'customer', 'read_at', '-created_at'], name='notif_customer_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', True), ('user__isnull', False)), models.Q(('customer__isnull', False), ('user__isnull', True)), _connector='OR'), name='notification_has_exactly_one_recipient'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False), ('user__isnull', False)), fields=('event', 'user'), name='unique_notification_per_event_and_user'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('customer__isnull', False), ('event__isnull', False)), fields=('event', 'customer'), name='unique_notification_per_event_and_customer'),
        ),
    ]
