# Generated by Django 5.2.17 on 2026-09-03 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_standard_preset_parity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(max_length=4000)),
                ('priority', models.CharField(choices=[('info', 'Informativa'), ('action', 'Requiere acción'), ('warning', 'Advertencia'), ('critical', 'Crítica')], default='info', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('cancelled', 'Descartado')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_announcements', to=settings.AUTH_USER_MODEL)),
                ('source_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_announcements', to='store.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAudienceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('all_company', 'Toda la empresa'), ('branch', 'Sucursal'), ('role', 'Rol'), ('capability', 'Capacidad'), ('user', 'Personas')], max_length=16)),
                ('capability_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_rules', to='store.announcement')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_rules', to='store.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_rules', to='store.company')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_rules', to='store.companyrole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['source_company', 'status', '-created_at'], name='store_annou_source__a52f00_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', '-published_at'], name='store_annou_status_3cae6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('status', 'published')), models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', True)), _connector='OR'), name='announcement_published_has_a_timestamp'),
        ),
        migrations.AddIndex(
            model_name='announcementaudiencerule',
            index=models.Index(fields=['announcement', 'company'], name='store_annou_announc_24bfc3_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementaudiencerule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('branch__isnull', True), ('capability_code', ''), ('kind', 'all_company'), ('role__isnull', True), ('user__isnull', True)), models.Q(('branch__isnull', False), ('capability_code', ''), ('kind', 'branch'), ('role__isnull', True), ('user__isnull', True)), models.Q(('branch__isnull', True), ('capability_code', ''), ('kind', 'role'), ('role__isnull', False), ('user__isnull', True)), models.Q(('capability_code__gt', ''), ('kind', 'capability'), ('branch__isnull', True), ('role__isnull', True), ('user__isnull', True)), models.Q(('branch__isnull', True), ('capability_code', ''), ('kind', 'user'), ('role__isnull', True), ('user__isnull', False)), _connector='OR'), name='audience_rule_matches_its_kind'),
        ),
    ]
