# Generated by Django 5.2.17 on 2026-09-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_pilot_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='logo_horizontal_on_dark_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo_horizontal_on_light_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo_on_dark_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo_on_light_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
