# Generated by Django 5.2.17 on 2026-09-03 20:03

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_pilot_logo_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='light_background_color',
            field=models.CharField(blank=True, max_length=7, validators=[store.models.validate_hex_color]),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='light_surface_color',
            field=models.CharField(blank=True, max_length=7, validators=[store.models.validate_hex_color]),
        ),
    ]
