# Generated by Django 5.2.17 on 2026-09-03 20:30

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_pilot_light_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='logo_horizontal_on_dark_url',
            field=models.CharField(blank=True, max_length=500, validators=[store.models.validate_asset_url]),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='logo_horizontal_on_light_url',
            field=models.CharField(blank=True, max_length=500, validators=[store.models.validate_asset_url]),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='logo_on_dark_url',
            field=models.CharField(blank=True, max_length=500, validators=[store.models.validate_asset_url]),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='logo_on_light_url',
            field=models.CharField(blank=True, max_length=500, validators=[store.models.validate_asset_url]),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500, validators=[store.models.validate_asset_url]),
        ),
    ]
