# Generated by Django 5.2.17 on 2026-09-03 22:01

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_asset_url_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=80)),
                ('hero_title', models.CharField(blank=True, max_length=160)),
                ('hero_subtitle', models.TextField(blank=True, max_length=400)),
                ('hero_primary_cta_label', models.CharField(blank=True, max_length=40)),
                ('hero_primary_cta_url', models.CharField(blank=True, max_length=500, validators=[store.models.validate_cta_url])),
                ('hero_secondary_cta_label', models.CharField(blank=True, max_length=40)),
                ('hero_secondary_cta_url', models.CharField(blank=True, max_length=500, validators=[store.models.validate_cta_url])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_page', to='store.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_storefront_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'configuración de portada',
                'verbose_name_plural': 'configuraciones de portada',
            },
        ),
        migrations.CreateModel(
            name='StorefrontCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('home_hero', 'Portada — bloque principal'), ('home_featured', 'Portada — destacado'), ('home_promo', 'Portada — promoción'), ('home_bottom_promo', 'Portada — promoción inferior')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('archived', 'Archivada')], db_index=True, default='draft', max_length=16)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True, max_length=600)),
                ('image_url', models.CharField(blank=True, max_length=500, validators=[store.models.validate_asset_url])),
                ('cta_label', models.CharField(blank=True, max_length=40)),
                ('cta_url', models.CharField(blank=True, max_length=500, validators=[store.models.validate_cta_url])),
                ('secondary_cta_label', models.CharField(blank=True, max_length=40)),
                ('secondary_cta_url', models.CharField(blank=True, max_length=500, validators=[store.models.validate_cta_url])),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_campaigns', to='store.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_storefront_campaigns', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storefront_campaigns', to='store.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_storefront_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot', '-priority', '-published_at', '-id'],
                'indexes': [models.Index(fields=['company', 'slot', 'status'], name='store_store_company_f3d5e4_idx'), models.Index(fields=['company', 'status', 'starts_at', 'ends_at'], name='store_store_company_f83b62_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('status', 'published')), models.Q(('status', 'published'), _negated=True), _connector='OR'), name='storefront_campaign_published_has_a_timestamp'), models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='storefront_campaign_window_is_ordered')],
            },
        ),
    ]
