# Generated by Django 5.2.17 on 2026-09-03 22:00

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_storefront_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='logo_isotype_on_dark_url',
            field=models.CharField(blank=True, max_length=500, validators=[store.models.validate_asset_url]),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo_isotype_on_light_url',
            field=models.CharField(blank=True, max_length=500, validators=[store.models.validate_asset_url]),
        ),
    ]
