# Generated by Django 5.2.17 on 2026-09-03 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_pilot_storefront_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefrontcampaign',
            name='body',
            field=models.TextField(blank=True, max_length=600, validators=[django.core.validators.MaxLengthValidator(600)]),
        ),
        migrations.AlterField(
            model_name='storefrontpagesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, max_length=400, validators=[django.core.validators.MaxLengthValidator(400)]),
        ),
    ]
