# Generated by Django 5.2.17 on 2026-09-04 15:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_text_length_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storefrontpagesettings',
            name='services_hero_subtitle',
            field=models.TextField(blank=True, max_length=400, validators=[django.core.validators.MaxLengthValidator(400)]),
        ),
        migrations.AddField(
            model_name='storefrontpagesettings',
            name='services_hero_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='storefrontpagesettings',
            name='services_warranty_note',
            field=models.TextField(blank=True, max_length=600, validators=[django.core.validators.MaxLengthValidator(600)]),
        ),
        migrations.CreateModel(
            name='StorefrontFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(max_length=1200, validators=[django.core.validators.MaxLengthValidator(1200)])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_faqs', to='store.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_storefront_faqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['company', 'is_active', 'sort_order'], name='store_store_company_f0bc4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StorefrontServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=400, validators=[django.core.validators.MaxLengthValidator(400)])),
                ('devices_text', models.CharField(blank=True, max_length=120)),
                ('estimated_time_text', models.CharField(blank=True, max_length=40)),
                ('highlight', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_services', to='store.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_storefront_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['company', 'is_active', 'sort_order'], name='store_store_company_a5ceeb_idx')],
            },
        ),
        migrations.CreateModel(
            name='StorefrontTrustMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=24)),
                ('label', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_metrics', to='store.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_storefront_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['company', 'is_active', 'sort_order'], name='store_store_company_020c8f_idx')],
            },
        ),
    ]
