# Generated by Django 5.2.17 on 2026-09-06 05:51

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0080_backfill_order_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('01', 'Factura electrónica'), ('03', 'Boleta de venta electrónica')], db_index=True, max_length=2)),
                ('series', models.CharField(max_length=4, validators=[store.models.validate_fiscal_series])),
                ('next_number', models.PositiveBigIntegerField(default=1)),
                ('environment', models.CharField(choices=[('beta', 'Pruebas (SUNAT beta)'), ('production', 'Producción')], default='beta', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_series', to='store.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_series', to='store.company')),
            ],
            options={
                'verbose_name': 'Serie fiscal',
                'verbose_name_plural': 'Series fiscales',
            },
        ),
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('01', 'Factura electrónica'), ('03', 'Boleta de venta electrónica')], max_length=2)),
                ('series', models.CharField(max_length=4)),
                ('number', models.PositiveBigIntegerField()),
                ('issued_at', models.DateTimeField()),
                ('environment', models.CharField(choices=[('beta', 'Pruebas (SUNAT beta)'), ('production', 'Producción')], max_length=16)),
                ('issuer_tax_id', models.CharField(max_length=15)),
                ('issuer_legal_name', models.CharField(max_length=255)),
                ('issuer_trade_name', models.CharField(blank=True, max_length=255)),
                ('issuer_address', models.CharField(blank=True, max_length=255)),
                ('customer_doc_type', models.CharField(max_length=2)),
                ('customer_doc_number', models.CharField(max_length=20)),
                ('customer_legal_name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de generar'), ('generated', 'XML generado'), ('signed', 'Firmado'), ('submitted', 'Enviado'), ('accepted', 'Aceptado por SUNAT'), ('accepted_observed', 'Aceptado con observaciones'), ('rejected', 'Rechazado por SUNAT'), ('submission_error', 'Error de envío')], db_index=True, default='pending', max_length=24)),
                ('signed_xml', models.TextField(blank=True)),
                ('signed_xml_sha256', models.CharField(blank=True, max_length=64)),
                ('digest_value', models.CharField(blank=True, max_length=128)),
                ('cdr_xml', models.TextField(blank=True)),
                ('cdr_sha256', models.CharField(blank=True, max_length=64)),
                ('sunat_response_code', models.CharField(blank=True, max_length=8)),
                ('sunat_response_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='store.company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='store.order')),
                ('series_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='store.fiscalseries')),
            ],
            options={
                'verbose_name': 'Comprobante electrónico',
                'verbose_name_plural': 'Comprobantes electrónicos',
            },
        ),
        migrations.CreateModel(
            name='FiscalSubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('environment', models.CharField(choices=[('beta', 'Pruebas (SUNAT beta)'), ('production', 'Producción')], max_length=16)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(max_length=32)),
                ('response_code', models.CharField(blank=True, max_length=8)),
                ('safe_message', models.CharField(blank=True, max_length=500)),
                ('request_sha256', models.CharField(blank=True, max_length=64)),
                ('response_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='store.fiscaldocument')),
            ],
            options={
                'verbose_name': 'Intento de envío fiscal',
                'verbose_name_plural': 'Intentos de envío fiscal',
                'ordering': ['document', 'attempt_number'],
            },
        ),
        migrations.AddIndex(
            model_name='fiscalseries',
            index=models.Index(fields=['company', 'document_type', 'is_active'], name='store_fisca_company_5f7c1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalseries',
            constraint=models.UniqueConstraint(fields=('company', 'document_type', 'series', 'environment'), name='fiscal_series_unique_per_company_env'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['company', 'status'], name='store_fisca_company_076db9_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['company', 'issued_at'], name='store_fisca_company_04d588_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.UniqueConstraint(fields=('company', 'document_type', 'series', 'number', 'environment'), name='fiscal_document_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'rejected'), _negated=True), fields=('order',), name='fiscal_document_one_live_per_order'),
        ),
        migrations.AddConstraint(
            model_name='fiscalsubmissionattempt',
            constraint=models.UniqueConstraint(fields=('document', 'attempt_number'), name='fiscal_attempt_unique_number'),
        ),
    ]
