# Generated by Django 5.2.17 on 2026-09-10 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0082_fiscal_capabilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('branch_access_mode', models.CharField(choices=[('all', 'Todas las sucursales'), ('selected', 'Sucursales seleccionadas')], default='all', max_length=16)),
                ('branch_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('revoked', 'Revocada')], db_index=True, default='pending', max_length=16)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_invitations', to='store.companyarea')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invitations', to='store.company')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_invitations', to='store.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_invitations', to='store.companyrole')),
            ],
            options={
                'verbose_name': 'Invitación de personal',
                'verbose_name_plural': 'Invitaciones de personal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='store_staff_company_7f62ef_idx'), models.Index(fields=['token_hash'], name='store_staff_token_h_d565a8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('company', 'email'), name='staff_invitation_one_pending_per_email')],
            },
        ),
    ]
