# Generated by Django 5.2.17 on 2026-09-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0084_userprofile_tokens_valid_after_revokedaccesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('correlativo', models.PositiveBigIntegerField()),
                ('reference_date', models.DateField(db_index=True)),
                ('issue_date', models.DateField()),
                ('environment', models.CharField(choices=[('beta', 'Pruebas (SUNAT beta)'), ('production', 'Producción')], max_length=16)),
                ('status', models.CharField(choices=[('generated', 'Generado'), ('signed', 'Firmado'), ('submitted', 'Enviado (ticket recibido)'), ('accepted', 'Aceptado por SUNAT'), ('accepted_observed', 'Aceptado con observaciones'), ('rejected', 'Rechazado por SUNAT'), ('submission_error', 'Error de envío')], db_index=True, default='generated', max_length=24)),
                ('signed_xml', models.TextField(blank=True)),
                ('signed_xml_sha256', models.CharField(blank=True, max_length=64)),
                ('ticket', models.CharField(blank=True, max_length=100)),
                ('submitting_since', models.DateTimeField(blank=True, null=True)),
                ('cdr_xml', models.TextField(blank=True)),
                ('cdr_sha256', models.CharField(blank=True, max_length=64)),
                ('sunat_response_code', models.CharField(blank=True, max_length=8)),
                ('sunat_response_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_daily_summaries', to='store.company')),
            ],
            options={
                'verbose_name': 'Resumen diario de boletas',
                'verbose_name_plural': 'Resúmenes diarios de boletas',
            },
        ),
        migrations.CreateModel(
            name='FiscalDailySummaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.PositiveIntegerField()),
                ('condition_code', models.CharField(default='1', max_length=1)),
                ('superseded', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summary_inclusions', to='store.fiscaldocument')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='store.fiscaldailysummary')),
            ],
            options={
                'verbose_name': 'Boleta en resumen diario',
                'verbose_name_plural': 'Boletas en resumen diario',
                'ordering': ['summary', 'line_id'],
            },
        ),
        migrations.AddIndex(
            model_name='fiscaldailysummary',
            index=models.Index(fields=['company', 'status'], name='store_fisca_company_cc03a6_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldailysummary',
            index=models.Index(fields=['company', 'reference_date'], name='store_fisca_company_69c21d_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldailysummary',
            constraint=models.UniqueConstraint(fields=('company', 'environment', 'reference_date', 'correlativo'), name='fiscal_summary_unique_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldailysummary',
            constraint=models.UniqueConstraint(fields=('company', 'environment', 'identifier'), name='fiscal_summary_unique_identifier'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldailysummarydocument',
            constraint=models.UniqueConstraint(fields=('summary', 'document'), name='fiscal_summary_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldailysummarydocument',
            constraint=models.UniqueConstraint(fields=('summary', 'line_id'), name='fiscal_summary_line_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldailysummarydocument',
            constraint=models.UniqueConstraint(condition=models.Q(('superseded', False)), fields=('document',), name='fiscal_summary_one_active_per_document'),
        ),
    ]
