# Generated by Django 5.2.17 on 2026-09-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0085_fiscaldailysummary_fiscaldailysummarydocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscaldailysummary',
            name='status',
            field=models.CharField(choices=[('generated', 'Generado'), ('signed', 'Firmado'), ('submitted', 'Enviado (ticket recibido)'), ('accepted', 'Aceptado por SUNAT'), ('accepted_observed', 'Aceptado con observaciones'), ('rejected', 'Rechazado por SUNAT'), ('submission_error', 'Error de envío (no transmitido)'), ('submission_unknown', 'Envío con resultado incierto')], db_index=True, default='generated', max_length=24),
        ),
    ]
