# Generated by Django 5.2.17 on 2026-09-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0086_alter_fiscaldailysummary_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fiscaldailysummary',
            name='fiscal_summary_unique_correlativo',
        ),
        migrations.AddConstraint(
            model_name='fiscaldailysummary',
            constraint=models.UniqueConstraint(fields=('company', 'environment', 'issue_date', 'correlativo'), name='fiscal_summary_unique_correlativo'),
        ),
    ]
