# Generated by Django 5.2.17 on 2026-09-23 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0087_remove_fiscaldailysummary_fiscal_summary_unique_correlativo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fiscaldocument',
            name='fiscal_document_one_live_per_order',
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='note_reason_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='note_reason_description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='note_request_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='original_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='store.fiscaldocument'),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='document_type',
            field=models.CharField(choices=[('01', 'Factura electrónica'), ('03', 'Boleta de venta electrónica'), ('07', 'Nota de crédito electrónica'), ('08', 'Nota de débito electrónica')], max_length=2),
        ),
        migrations.AlterField(
            model_name='fiscalseries',
            name='document_type',
            field=models.CharField(choices=[('01', 'Factura electrónica'), ('03', 'Boleta de venta electrónica'), ('07', 'Nota de crédito electrónica'), ('08', 'Nota de débito electrónica')], db_index=True, max_length=2),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), ('document_type__in', ['01', '03'])), fields=('order',), name='fiscal_document_one_live_per_order'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('note_request_key', ''), _negated=True), models.Q(('status', 'rejected'), _negated=True)), fields=('original_document', 'note_request_key'), name='fiscal_note_idempotent_per_original'),
        ),
    ]
