# Generated by Django 5.2.17 on 2026-09-24 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0088_remove_fiscaldocument_fiscal_document_one_live_per_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscaldocument',
            name='cdr_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_documents_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='granted_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='granted_method',
            field=models.CharField(blank=True, choices=[('ecommerce_portal', 'Puesto a disposición en el portal'), ('email', 'Enviado por correo electrónico'), ('pos_print', 'Impreso y entregado en mostrador'), ('pos_electronic', 'Entregado electrónicamente en mostrador'), ('manual', 'Registrado manualmente por un operador'), ('api', 'Entregado por una integración')], max_length=20),
        ),
    ]
