# Generated by Django 5.2.17 on 2026-09-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0089_fiscal_cdr_accepted_at_and_grant_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalVoidCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('correlativo', models.PositiveBigIntegerField()),
                ('reference_date', models.DateField(db_index=True)),
                ('issue_date', models.DateField()),
                ('environment', models.CharField(choices=[('beta', 'Pruebas (SUNAT beta)'), ('production', 'Producción')], max_length=16)),
                ('status', models.CharField(choices=[('generated', 'XML generado'), ('signed', 'Firmado'), ('submitted', 'Enviado (ticket recibido)'), ('accepted', 'Aceptada por SUNAT'), ('accepted_observed', 'Aceptada con observaciones'), ('rejected', 'Rechazada por SUNAT'), ('submission_error', 'Error de envío (no transmitido)'), ('submission_unknown', 'Envío con resultado incierto')], db_index=True, default='generated', max_length=24)),
                ('signed_xml', models.TextField(blank=True)),
                ('signed_xml_sha256', models.CharField(blank=True, max_length=64)),
                ('ticket', models.CharField(blank=True, max_length=100)),
                ('submitting_since', models.DateTimeField(blank=True, null=True)),
                ('cdr_xml', models.TextField(blank=True)),
                ('cdr_sha256', models.CharField(blank=True, max_length=64)),
                ('sunat_response_code', models.CharField(blank=True, max_length=8)),
                ('sunat_response_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_void_communications', to='store.company')),
            ],
            options={
                'verbose_name': 'Comunicación de baja',
                'verbose_name_plural': 'Comunicaciones de baja',
            },
        ),
        migrations.CreateModel(
            name='FiscalVoidCommunicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.PositiveIntegerField()),
                ('void_reason', models.CharField(max_length=100)),
                ('superseded', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='void_inclusions', to='store.fiscaldocument')),
                ('void_communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='store.fiscalvoidcommunication')),
            ],
            options={
                'verbose_name': 'Comprobante en comunicación de baja',
                'verbose_name_plural': 'Comprobantes en comunicación de baja',
                'ordering': ['void_communication', 'line_id'],
            },
        ),
        migrations.AddIndex(
            model_name='fiscalvoidcommunication',
            index=models.Index(fields=['company', 'status'], name='store_fisca_company_4097f4_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalvoidcommunication',
            index=models.Index(fields=['company', 'reference_date'], name='store_fisca_company_c202c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalvoidcommunication',
            constraint=models.UniqueConstraint(fields=('company', 'environment', 'issue_date', 'correlativo'), name='fiscal_void_unique_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='fiscalvoidcommunication',
            constraint=models.UniqueConstraint(fields=('company', 'environment', 'identifier'), name='fiscal_void_unique_identifier'),
        ),
        migrations.AddConstraint(
            model_name='fiscalvoidcommunicationdocument',
            constraint=models.UniqueConstraint(fields=('void_communication', 'document'), name='fiscal_void_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='fiscalvoidcommunicationdocument',
            constraint=models.UniqueConstraint(fields=('void_communication', 'line_id'), name='fiscal_void_line_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='fiscalvoidcommunicationdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('superseded', False)), fields=('document',), name='fiscal_void_one_active_per_document'),
        ),
    ]
