# Generated by Django 5.2.17 on 2026-09-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0090_fiscal_void_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalvoidcommunication',
            name='request_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='fiscalvoidcommunication',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('request_key', ''), _negated=True), models.Q(('status', 'rejected'), _negated=True)), fields=('company', 'environment', 'request_key'), name='fiscal_void_idempotent_request'),
        ),
    ]
