# Generated by Django 5.2.17 on 2026-09-28 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0091_fiscal_void_request_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscaldocument',
            name='not_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='not_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_documents_attested_not_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='not_granted_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.CheckConstraint(condition=models.Q(('granted_at__isnull', False), ('not_granted_at__isnull', False), _negated=True), name='fiscal_document_grant_is_exclusive'),
        ),
    ]
