# Generated by Django 5.2.17 on 2026-10-03 08:48

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0095_service_payments_collect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500, validators=[store.models.validate_asset_url]),
        ),
        migrations.AddField(
            model_name='storefrontpagesettings',
            name='hero_image_url',
            field=models.CharField(blank=True, default='', max_length=500, validators=[store.models.validate_asset_url]),
        ),
        migrations.AddField(
            model_name='storefrontpagesettings',
            name='hero_variant',
            field=models.CharField(choices=[('dark', 'Oscuro'), ('light', 'Claro')], default='dark', max_length=8),
        ),
        migrations.CreateModel(
            name='StorefrontImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('storage_key', models.CharField(editable=False, max_length=255, unique=True)),
                ('mime_type', models.CharField(max_length=32)),
                ('byte_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('has_alpha', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_images', to='store.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_storefront_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'imagen de la tienda',
                'verbose_name_plural': 'imágenes de la tienda',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
