# Generated by Django 5.2.17 on 2026-10-04 16:30

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0097_storefront_section_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='document_logo_url',
            field=models.CharField(blank=True, max_length=500, validators=[store.models.validate_asset_url]),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='logo_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='logo_storage_key',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
