# Generated by Django 5.2.17 on 2026-10-04 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0098_fiscal_document_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('token_hint', models.CharField(editable=False, max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_agents', to='store.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_agents', to='store.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['branch_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('connection', models.CharField(choices=[('network', 'Red (cable o Wi-Fi, puerto 9100)')], default='network', max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=9100)),
                ('paper_width_mm', models.PositiveSmallIntegerField(default=80)),
                ('encoding', models.CharField(default='cp858', max_length=20)),
                ('auto_print', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printers', to='store.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printers', to='store.company')),
            ],
            options={
                'ordering': ['branch_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fiscal_ticket', 'Comprobante electrónico (80 mm)'), ('sales_note_ticket', 'Nota de venta (80 mm)')], max_length=30)),
                ('reason', models.CharField(choices=[('auto', 'Automático, al confirmarse la venta'), ('manual', 'Reimpresión pedida por una persona')], default='auto', max_length=10)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'En cola'), ('printing', 'Enviado a la impresora'), ('printed', 'Impreso'), ('failed', 'Falló'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('claim_token', models.CharField(blank=True, editable=False, max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='store.branch')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='store.printagent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='store.company')),
                ('fiscal_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='store.fiscaldocument')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='store.order')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='store.printer')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='store.salesnote')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='printer',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='printer_unique_name_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='printer',
            constraint=models.UniqueConstraint(condition=models.Q(('auto_print', True), ('is_active', True)), fields=('branch',), name='printer_one_auto_per_branch'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['branch', 'status', 'id'], name='store_print_branch__f59608_idx'),
        ),
        migrations.AddConstraint(
            model_name='printjob',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='print_job_idempotency_per_company'),
        ),
    ]
