# Generated by Django 5.2.17 on 2026-10-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0100_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairevidence',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='repairevidence',
            name='stage',
            field=models.CharField(choices=[('intake', 'Ingreso'), ('diagnosis', 'Diagnóstico'), ('repair_before', 'Antes de reparar'), ('repair_during', 'Durante la reparación'), ('repair_after', 'Después de reparar'), ('parts', 'Repuestos'), ('quality', 'Control de calidad'), ('ready', 'Listo para entrega'), ('delivery', 'Entrega'), ('warranty', 'Garantía / reingreso'), ('other', 'Otra')], db_index=True, max_length=20),
        ),
    ]
