# Generated by Django 5.2.17 on 2026-10-05 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0101_evidence_caption_and_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='identifiers_pending_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='imei2',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'imei2'], name='store_devic_company_d2e8f8_idx'),
        ),
    ]
