# Generated by Django 5.2.17 on 2026-10-05 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0102_device_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repairquote',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairquotedecision',
            name='note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='repairquotedecision',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_quote_decisions_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repairquotedecision',
            name='source',
            field=models.CharField(choices=[('customer', 'El cliente'), ('staff', 'Registrada por el personal')], default='customer', max_length=16),
        ),
        migrations.AlterField(
            model_name='repairquote',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Anulada'), ('superseded', 'Reemplazada')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='repairquotedecision',
            name='channel',
            field=models.CharField(choices=[('customer_account', 'Cuenta del cliente'), ('tracking_link', 'Enlace de seguimiento'), ('staff_in_person', 'Presencial'), ('staff_phone', 'Llamada'), ('staff_whatsapp', 'WhatsApp'), ('staff_other', 'Otro')], default='customer_account', max_length=32),
        ),
        migrations.CreateModel(
            name='RepairTrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_tracking_links', to='store.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_tracking_links_created', to=settings.AUTH_USER_MODEL)),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='store.repairorder')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_tracking_links_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('repair_order',), name='one_live_tracking_link_per_order')],
            },
        ),
    ]
