# Generated by Django 5.2.17 on 2026-10-05 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0104_grant_quote_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp_opt_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_opt_in_source',
            field=models.CharField(blank=True, choices=[('counter', 'En el mostrador'), ('web', 'Desde la web'), ('message', 'Por mensaje')], max_length=16),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_opt_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='recipient_masked',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=[('email', 'Correo'), ('whatsapp', 'WhatsApp')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('delivered', 'Entregada'), ('read', 'Leída'), ('failed', 'Fallida'), ('skipped', 'Omitida')], db_index=True, default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='CompanyMessagingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('whatsapp_provider', models.CharField(choices=[('cloud_api', 'WhatsApp Cloud API (Meta)')], default='cloud_api', max_length=24)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=40)),
                ('whatsapp_business_account_id', models.CharField(blank=True, max_length=40)),
                ('whatsapp_access_token_env', models.CharField(blank=True, max_length=64)),
                ('whatsapp_app_secret_env', models.CharField(blank=True, max_length=64)),
                ('whatsapp_verify_token_env', models.CharField(blank=True, max_length=64)),
                ('default_calling_code', models.CharField(blank=True, max_length=4)),
                ('template_language', models.CharField(default='es', max_length=10)),
                ('whatsapp_templates', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_settings', to='store.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de mensajería',
                'verbose_name_plural': 'Configuraciones de mensajería',
            },
        ),
    ]
