# Generated by Django 5.2.17 on 2026-10-05 12:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0105_whatsapp_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_serialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_imei',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StockUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=40)),
                ('imei', models.CharField(blank=True, max_length=15, null=True)),
                ('imei2', models.CharField(blank=True, max_length=15, null=True)),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('open_box', 'Caja abierta'), ('refurbished', 'Reacondicionado'), ('used', 'Usado')], default='new', max_length=16)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Apartado'), ('sold', 'Vendido'), ('written_off', 'Dado de baja')], db_index=True, default='available', max_length=16)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_units', to='store.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_units', to='store.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_units', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_units', to='store.product')),
            ],
            options={
                'ordering': ['-received_at', '-pk'],
                'indexes': [models.Index(fields=['company', 'branch', 'product', 'status'], name='stock_unit_scope_idx'), models.Index(fields=['company', 'serial_number'], name='stock_unit_serial_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'product', 'serial_number'), name='unique_stock_unit_serial_per_product'), models.UniqueConstraint(condition=models.Q(('imei__isnull', False)), fields=('company', 'imei'), name='unique_stock_unit_imei_per_company'), models.UniqueConstraint(condition=models.Q(('imei2__isnull', False)), fields=('company', 'imei2'), name='unique_stock_unit_imei2_per_company'), models.CheckConstraint(condition=models.Q(models.Q(('imei', ''), _negated=True), models.Q(('imei2', ''), _negated=True), models.Q(('serial_number', ''), _negated=True)), name='stock_unit_identifiers_null_not_blank')],
            },
        ),
    ]
