# Generated by Django 5.2.17 on 2026-10-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0106_serialized_stock_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_home',
            field=models.BooleanField(default=True),
        ),
    ]
