# Generated by Django 5.2.17 on 2026-10-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0109_backfill_tracking_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkimportjob',
            name='import_type',
            field=models.CharField(choices=[('products', 'Productos'), ('stock', 'Inventario'), ('units', 'Equipos con serie')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='importmappingprofile',
            name='import_type',
            field=models.CharField(choices=[('products', 'Productos'), ('stock', 'Inventario'), ('units', 'Equipos con serie')], db_index=True, max_length=16),
        ),
    ]
