# Generated by Django 5.2.17 on 2026-10-06 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0110_bulk_import_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=40)),
                ('slot', models.CharField(choices=[('active', 'Activa'), ('draft', 'Borrador')], max_length=8)),
                ('enabled', models.BooleanField(default=False)),
                ('public', models.JSONField(blank=True, default=dict)),
                ('sealed_secrets', models.TextField(blank=True)),
                ('secret_meta', models.JSONField(blank=True, default=dict)),
                ('validated', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, max_length=40)),
                ('last_test_message', models.CharField(blank=True, max_length=300)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_configs', to='store.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('provider', 'company', 'slot'), name='unique_integration_config_per_company'), models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('provider', 'slot'), name='unique_integration_config_platform')],
            },
        ),
    ]
