# Generated by Django 5.2.17 on 2026-10-07 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0111_integration_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('ga_client_id', models.CharField(blank=True, max_length=64)),
                ('ga_session_id', models.CharField(blank=True, max_length=32)),
                ('fbp', models.CharField(blank=True, max_length=128)),
                ('fbc', models.CharField(blank=True, max_length=255)),
                ('ttp', models.CharField(blank=True, max_length=128)),
                ('ttclid', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_context', to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('event', models.CharField(default='purchase', max_length=32)),
                ('event_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sending', 'Enviándose'), ('sent', 'Enviada'), ('failed', 'Fallida'), ('skipped', 'Omitida')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_kind', models.CharField(blank=True, max_length=32)),
                ('provider_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='store.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'provider', 'event'), name='unique_conversion_per_order_provider_event')],
            },
        ),
    ]
