# Generated by Django 5.2.17 on 2026-10-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0112_measurement_conversions'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttoken',
            name='code_attempts',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='accounttoken',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounttoken',
            name='code_hash',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
    ]
