# Generated by Django 5.2.17 on 2026-10-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0112_measurement_conversions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published_online',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
